FROM golang:1.17

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

RUN go get -d -v ./... && go install -v ./...
RUN go get -u github.com/gorilla/mux && go get -u github.com/go-sql-driver/mysql

CMD ["app"]